🧸 Break the build. Add a failing test.
    slt-acorn-plugin 🍀 node --test
    file:///data/data/com.termux/files/home/slt-acorn-plugin/test/index.js:4
    import { sltPlugin } from "../index.js";
             ^^^^^^^^^
    SyntaxError: The requested module '../index.js' does not provide an export named 'sltPlugin'                    at #_instantiate (node:internal/modules/esm/module_job:254:21)
        at async ModuleJob.run (node:internal/modules/esm/module_job:369:5)
        at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:689:26)                          at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5)                                                                               Node.js v24.9.0
    ✖ test/index.js (483.405ms)
    ℹ tests 1
    ℹ suites 0
    ℹ pass 0
    ℹ fail 1
    ℹ cancelled 0
    ℹ skipped 0
    ℹ todo 0
    ℹ duration_ms 559.859462

    ✖ failing tests:

    test at test/index.js:1:1                             ✖ test/index.js (483.405ms)
      'test failed'